# Generated by Django 4.1.7 on 2023-04-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='image', upload_to='ads/'),
            preserve_default=False,
        ),
    ]
