# Generated by Django 4.1.7 on 2023-04-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='owner',
            new_name='author',
        ),
    ]
