# Generated by Django 4.1.7 on 2023-05-04 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
